#登陆相关配置
login:
  #开放的模拟登陆api服务器地址
  api: "http://www.zimo.wiki:8080/wisedu-unified-login-api-v1.0/api/login"
#用户组配置
users:
  #单个用户配置
  - user:
      #username 学号或者工号
      用户名：'112017701003861’
      #password密码（）身份证后六位
      password: '104319'
      #address 地址，定位信息
      address: 中国重庆市北碚区融汇中路
      #email 接受通知消息的邮箱
      电子邮件：18753364336@163.com
      #school学校全称
      school: 西南大学
      #lon 经度
      lon: '106.4304918'
      #lat 纬度
      lat: '29.8281573'
      #abnormalReason 反馈信息
      abnormalReason:
      #photo 签到照片，不需要可不填，或者直接删除
      photo:
  #多用户配置，将下面的注释去掉即可，如果有表单内容有图片，不建议使用多用户配置
#今日校园相关配置
cpdaily:

  #附加信息组默认选项配置，没有可留空
  defaults:
  #附加信息组默认选项配置，按顺序，可留空
  #    - default:
  #        #表单项标题
  #        title: 体温
  #        #表单项默认值
  #        value: 正常
  #多个额外选项配置
  - default:
      title: 研究生体温检测-早上
      value: 正常，＜37.2℃
#    - default:
#        #表单项标题
#        title: 体温
#        #表单项默认值
#        value: 正常
